---
title: "Doctoral Examination"
---

This page records my involvement as an examiner in the candidature of the Linguistics Doctoral Students at the Faculty of Humanities, Udayana University.

# Pre-proposal/qualification

## 2025/2026 (Odd Semester)

-   Made Suardika Jaya (Pre-proposal title: *Kajian Variasi Bahasa di Kalangan Akademisi Institut Agama Hindu Negeri Mpu Kuturan*) - Wednesday, 27 August 2025 (moved forward into 22 August 2025 at 13:00-15:00 WITA, Senate Meeting Room, Faculty of Humanities, Udayana University)

## 2024/2025 (Even Semester)

-   Gusti Ayu Praminatih (Pre-proposal title: *Penggunaan Strategi Metawacana Interpersonal dalam Membangun Daya Tarik Retoris pada Artikel Ilmiah Lintas Disiplin*) - Tuesday, 22 July 2025 (10:00-12:00 WITA, Poerbatjaraka Meeting Room, Faculty of Humanities, Udayana University)

## 2021/2022 (Odd Semester)

-   Ni Putu Ayu Pujiani (Pre-proposal title: *Sinonimi Verba Bahasa Inggris* \[Verbal Synonyms in English\])

# Proposal

## 2025/2026 (Odd Semester)

-   Made Suardika Jaya (Proposal title: *Kajian Variasi Leksikon Lisan di Kalangan Akademisi Institut Agama Hindu Negeri Mpu Kuturan*) - Thursday, 22 January 2026 (13:00-15:00 WITA, Poerbatjaraka Meeting Room, Faculty of Humanities, Udayana University)

-   Gusti Ayu Praminatih (Proposal title: *Penggunaan Strategi Metawacana Interpersonal pada Artikel Ilmiah Terbitan Springer Nature*) - Thursday, 13 November 2025 (13:00-14:00 WITA, Poerbatjaraka Meeting Room, Faculty of Humanities, Udayana University)

# Viva Voce

## 2024/2025 (Odd Semester)

-   Ni Putu Ayu Pujiani (Thesis title: *Verba ‘Perintah’ Bahasa Inggris* \[‘Command’ verbs in English\]) - [news](https://www.instagram.com/p/DFFZOr4Sj6o/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==)

-   Putu Weddha Savitri (Thesis title: *Ajektiva Bahasa Prancis Bermakna ‘luar biasa’: Analisis Semantik Berbasis Korpus* \[French Adjectives meaning ‘Extraordinary’: A corpus-based semantic analysis\]) - member of the [*CompLexico*](https://github.com/complexico) research group; [news](https://www.instagram.com/p/DEE-rbYTl3t/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==)
