---
title: "Co-authored publications"
---

This page records the history of my involvement in co-authored publication(s) with the Linguistics Doctoral Students at the Faculty of Humanities, Udayana University.

# 2025

- Widiastuti, Ni Made Ayu, I Made Rajeg, **Gede Primahadi Wijaya Rajeg**, Ketut Artawa & I Nyoman Udayana. 2025. [_Model analisis pola metaforis dan pemetaan metafora konseptual_](https://www.balinusacreative.com/product-details.php?id=001607). Denpasar, Bali, Indonesia: Bali Nusa Creative. (A part of doctoral dissertation project by the first author) - the first, second, third and the fourth authors are members of the [*CompLexico*](https://github.com/complexico) research group

# 2024

-   Widiastuti, Ni Made Ayu, Ketut Artawa, I Made Rajeg, I Nyoman Udayana & **Gede Primahadi Wijaya Rajeg**. 2024. Selecting representative data samples from corpus collection with specific target domains. *The International Journal of Social Sciences World (TIJOSSW)* 6(1). 225–237. ([Paper](https://www.growingscholar.org/journal/index.php/TIJOSSW/article/view/448)) - the first, second, third and last authors are members of the [*CompLexico*](https://github.com/complexico) research group

