---
title: "Doctoral Students"
---

This page records the history of my involvement in the candidature of the Linguistics Doctoral Students at the Faculty of Humanities, Udayana University.

# Examiner

## Pre-proposal/qualification

### 2021/2022 (Odd Semester)

-   Ni Putu Ayu Pujiani (Pre-proposal title: *Sinonimi Verba Bahasa Inggris* \[Verbal Synonyms in English\])

## Viva Voce

### 2024/2025 (Odd Semester)

-   Ni Putu Ayu Pujiani (Thesis title: *Verba ‘Perintah’ Bahasa Inggris* \[‘Command’ verbs in English\]) - [news](https://www.instagram.com/p/DFFZOr4Sj6o/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==)

-   Putu Weddha Savitri (Thesis title: *Ajektiva Bahasa Prancis Bermakna ‘luar biasa’: Analisis Semantik Berbasis Korpus* \[French Adjectives meaning ‘Extraordinary’: A corpus-based semantic analysis\]) - member of the [*CompLexico*](https://github.com/complexico) research group; [news](https://www.instagram.com/p/DEE-rbYTl3t/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==)

# Co-authoring

This section lists co-authored paper(s) with Doctoral students

## 2024

-   Widiastuti, Ni Made Ayu, Ketut Artawa, I Made Rajeg, I Nyoman Udayana & **Gede Primahadi Wijaya Rajeg**. 2024. Selecting representative data samples from corpus collection with specific target domains. *The International Journal of Social Sciences World (TIJOSSW)* 6(1). 225–237. - first, second, and third authors are members of the [*CompLexico*](https://github.com/complexico) research group
